In [8]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import MinMaxScaler
from keras.models import Sequential
from keras.layers import SimpleRNN, Dense
from sklearn.metrics import mean_squared_error
from sklearn.model_selection import train_test_split

In [9]:
df = pd.read_csv('usdrub.txt', sep=";")
df = df['<CLOSE>']

In [10]:
df = np.array(df).reshape(-1,1)
df

array([[59.2343],
       [59.1927],
       [59.2332],
       ...,
       [74.1308],
       [74.0699],
       [74.1201]])

In [11]:
scaler = MinMaxScaler()
df = scaler.fit_transform(df)

In [12]:
X = []
y = []

for i in range(50 , len(df)):
    X.append(df[i-50:i, 0])
    y.append(df[i, 0])


In [21]:
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42)
X_train= np.asarray(X_train)
X_test = np.asarray(X_test)
y_train = np.asarray(y_train)
y_test = np.asarray(y_test)

In [ ]:

split1 = 0.7
split2 = 0.9
border1 = int(df.shape[0]*split1)
border2 = int(df.shape[0]*split2)
X_train = X[: border1]
X_val = X[border1:border2]
X_test = X[border2:]
y_train = y[: border1]
y_val = y[border1:border2]
y_test = y[border2:]
X_train= np.asarray(X_train)
X_val= np.asarray(X_val)
X_test = np.asarray(X_test)
y_train = np.asarray(y_train)
y_val = np.asarray(y_val)
y_test = np.asarray(y_test)

In [22]:
model=Sequential()
model.add(SimpleRNN(100,activation='relu',input_shape=(50,1)))
model.add(Dense(1))

model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 simple_rnn_2 (SimpleRNN)    (None, 100)               10200     
                                                                 
 dense_2 (Dense)             (None, 1)                 101       
                                                                 
Total params: 10301 (40.24 KB)
Trainable params: 10301 (40.24 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [23]:
model.compile(optimizer='adam', loss = 'mse')

In [24]:
model.fit(X_train,y_train, epochs = 5, batch_size=8, validation_split=0.2)

Epoch 1/5
3252/3252 [==============================] - 120s 36ms/step - loss: 2.0411e-04 - val_loss: 3.0407e-05
Epoch 2/5
3252/3252 [==============================] - 113s 35ms/step - loss: 4.7076e-05 - val_loss: 3.0179e-05
Epoch 3/5
3252/3252 [==============================] - 115s 35ms/step - loss: 4.6105e-05 - val_loss: 3.1640e-05
Epoch 4/5
3252/3252 [==============================] - 114s 35ms/step - loss: 4.2600e-05 - val_loss: 2.4270e-04
Epoch 5/5
3252/3252 [==============================] - 112s 35ms/step - loss: 4.3879e-05 - val_loss: 3.3790e-05


In [25]:
y_pred = model.predict(X_test)
y_pred = scaler.inverse_transform(y_pred)
print(y_pred[:10])

339/339 [==============================] - 2s 6ms/step
[[73.90193 ]
 [65.59001 ]
 [65.72375 ]
 [65.38069 ]
 [66.15225 ]
 [66.76729 ]
 [59.966255]
 [65.892075]
 [63.735344]
 [64.573105]]


In [32]:
y_test = np.array(y_test).reshape(-1,1)
#y_test = scaler.inverse_transform(y_test)
print(y_test[:10])

[[73.8645]
 [65.5937]
 [65.698 ]
 [65.4415]
 [66.2308]
 [66.9306]
 [60.0466]
 [66.3005]
 [63.9742]
 [64.5574]]


In [31]:
y_test

array([[73.8645],
       [65.5937],
       [65.698 ],
       ...,
       [56.7225],
       [63.842 ],
       [64.3272]])

In [27]:
mean_squared_error(y_test, y_pred)

0.04508290700220757